flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- QuickCheck-2.8.1
- Stream-0.4.7.2
- arrows-0.4.4.1
- lazysmallcheck-0.6
- mtl-2.2.1
- primitive-0.6.1.0
- random-1.1
- tf-random-0.5
resolver: ghc-7.10.3
